### ISSUE TITLE
Unable to create file locally from YouTube

### ISSUE THREAD

**Issue by YU000jp** [usoonees/logseq-whisper-subtitles-server#1]
First, thank you for providing such a great plugin. I try and do not know how to use. It looks like the file isn't downloading.

What I did; Run from the menu of the block with "{{youtube URL}}".
Error message:
```
logseq-whisper-subtitle-server error: [Errno 2] No such file or directory: 
'D:\\ ------ \\logseq-whisper-subtitles-server\\logseq_whisper_subtitles_server\\.\\youtube/youtube_audio_6968954bf60841b48f987933359b93d3.mp3'
```
My guess is, the server is running. But the file was not found in the directory.

**Comment by YU000jp** [comment]
Additionally, server error message:
```
Downloading the video: https://www.youtube.com/watch?v=v3JX3mzrAoI into audio ...
Traceback (most recent call last):
  File "D:\------\logseq-whisper-subtitles-server\logseq_whisper_subtitles_server\app.py", line 29, in transcribe
    audio_path = download_youtube(youtube_url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\-----\logseq-whisper-subtitles-server\logseq_whisper_subtitles_server\services.py", line 54, in download_youtube
    audio_stream.download(filename=audio_name, output_path='.')
  File "C:\Python311\Lib\site-packages\pytube\streams.py", line 312, in download
    with open(file_path, "wb") as fh:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\-----\\logseq-whisper-subtitles-server\\logseq_whisper_subtitles_server\\.\\youtube/youtube_audio_735dad45a111435d9fdd69c81d90e9fa.mp3'
127.0.0.1 - - [15/Oct/2023 10:29:28] "POST /transcribe HTTP/1.1" 200 -
```

**Comment by usoonees** [comment]
Ah, I understand. The path usage on Windows is different from that on a Mac. I hadn't tested this before, but I'll work on resolving the issue tonight.

**Comment by usoonees** [comment]
> First, thank you for providing such a great plugin. I try and do not know how to use. It looks like the file isn't downloading.
> 
> What I did; Run from the menu of the block with "{{youtube URL}}". Error message:
> 
> ```
> logseq-whisper-subtitle-server error: [Errno 2] No such file or directory: 
> 'D:\\ ------ \\logseq-whisper-subtitles-server\\logseq_whisper_subtitles_server\\.\\youtube/youtube_audio_6968954bf60841b48f987933359b93d3.mp3'
> ```
> 
> My guess is, the server is running. But the file was not found in the directory.

Apologies for the inconvenience. There was a minor bug related to the file path. Could you please pull the latest version from the main branch and try again?

**Comment by YU000jp** [comment]
It seems like progress has been made. But...

Logseq error message: "not supported source yet"
https://github.com/usoonees/logseq-whisper-subtitles-server/blob/adfb039290675e2cef7c50b6408a42055729aba3/logseq_whisper_subtitles_server/app.py#L56

I used this URL. https://youtu.be/v3JX3mzrAoI (`{{youtube https://youtu.be/v3JX3mzrAoI}}`)


I'm not looking for an immediate solution, but just to report. I will also cooperate as much as possible. 🫡

**Comment by YU000jp** [comment]
https://github.com/usoonees/logseq-whisper-subtitles-server/blob/adfb039290675e2cef7c50b6408a42055729aba3/logseq_whisper_subtitles_server/app.py#L21

The cause of the problem has been found. The URL did not match the pattern. I will try fixing locally.

**Comment by usoonees** [comment]
@YU000jp Ah, I see the issue. It seems that the link was missing the "https://youtu.be/" prefix and only had "https://www.youtube.com/". Could you please pull the latest version and try again?
<img width="1175" alt="image" src="https://github.com/usoonees/logseq-whisper-subtitles-server/assets/56818734/a4478363-2c45-402f-8a0b-df789161c51f">

**Comment by YU000jp** [comment]
Two errors occurred.

1. "logseq-whisper-subtitle-server error: The size of tensor a (386) must match the size of tensor b (3) at non-singleton dimension 3"

1. logseq-whisper-subtitle-server error: cannot reshape tensor of 0 elements into shape [1, 0, 8, -1] because the unspecified dimension size -1 can be any value and is ambiguous

**Comment by usoonees** [comment]
Could you please provide me with the complete error stack?

**Comment by usoonees** [comment]
Can you run with the test audio?
```
cd logseq_whisper_subtitles_server
python services.py
```

**Comment by YU000jp** [comment]
It took some time, but it was reflected in Logseq. After waiting a few minutes, it appears that you received the processing.
I would like to be able to display messages being processed using "logseq.provideUI()".

**Comment by usoonees** [comment]
Yeah, you're right. The speed is tied to the local machine's capabilities. It's a bit slow on CPU; maybe a message should be displayed.

**Comment by usoonees** [comment]
Just outputting verbose logs to the console for now, which also means it could possibly switch to stream output for logseq, I will try to implement this.

**Comment by YU000jp** [comment]
Let me explain just in case. A popup will be displayed when use "logseq.provideUI()".

"logseq.provideUI()" sample code:
https://github.com/YU000jp/logseq-plugin-side-block/blob/31fa885980550180d569510a0d08f9699fca0ace/src/index.ts#L143

Process for remove the popup:
https://github.com/YU000jp/logseq-plugin-side-block/blob/31fa885980550180d569510a0d08f9699fca0ace/src/index.ts#L96C5-L96C95
