### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by DocSJ1980** [usoonees/logseq-whisper-subtitles-server#3]
Awesome concept. Really excited about it. 

Installation of the server went without an issue.

Running python services.py results in The system cannot find the file specified error as discussed in the previous issue. I checked the whole thread to find out how the issue was resolved but failed to find a definitive answer. that's why opening new issue.

```
(logseq-transcription) C:\Users\Hp Pavilion\Documents\MERNStack\third-party-repos\logseq-whisper-subtitles-server\logseq_whisper_subtitles_server>python services.py
Loading base whisper model...
Loading base whisper model done.
=== English audio test
Using model:  base
Transcribing Chinese simplified audio ...
C:\Users\Hp Pavilion\.conda\envs\logseq-transcription\Lib\site-packages\whisper\transcribe.py:114: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
Traceback (most recent call last):
  File "C:\Users\Hp Pavilion\Documents\MERNStack\third-party-repos\logseq-whisper-subtitles-server\logseq_whisper_subtitles_server\services.py", line 147, in <module>
    res_en = transcribe_audio("audio_english.mp3")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp Pavilion\Documents\MERNStack\third-party-repos\logseq-whisper-subtitles-server\logseq_whisper_subtitles_server\services.py", line 84, in transcribe_audio
    transcribe = model.transcribe(audio=audio_path, verbose=True, initial_prompt="对于普通话句子，以中文简体输出")  # 避免繁体输出
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp Pavilion\.conda\envs\logseq-transcription\Lib\site-packages\whisper\transcribe.py", line 121, in transcribe
    mel = log_mel_spectrogram(audio, padding=N_SAMPLES)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp Pavilion\.conda\envs\logseq-transcription\Lib\site-packages\whisper\audio.py", line 140, in log_mel_spectrogram
    audio = load_audio(audio)
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp Pavilion\.conda\envs\logseq-transcription\Lib\site-packages\whisper\audio.py", line 59, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp Pavilion\.conda\envs\logseq-transcription\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hp Pavilion\.conda\envs\logseq-transcription\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Hp Pavilion\.conda\envs\logseq-transcription\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by usoonees** [comment]
> Awesome concept. Really excited about it. 
> 
> 
> 
> Installation of the server went without an issue.
> 
> 
> 
> Running python services.py results in The system cannot find the file specified error as discussed in the previous issue. I checked the whole thread to find out how the issue was resolved but failed to find a definitive answer. that's why opening new issue.
> 
> 
> 
> ```
> 
> (logseq-transcription) C:\Users\Hp Pavilion\Documents\MERNStack\third-party-repos\logseq-whisper-subtitles-server\logseq_whisper_subtitles_server>python services.py
> 
> Loading base whisper model...
> 
> Loading base whisper model done.
> 
> === English audio test
> 
> Using model:  base
> 
> Transcribing Chinese simplified audio ...
> 
> C:\Users\Hp Pavilion\.conda\envs\logseq-transcription\Lib\site-packages\whisper\transcribe.py:114: UserWarning: FP16 is not supported on CPU; using FP32 instead
> 
>   warnings.warn("FP16 is not supported on CPU; using FP32 instead")
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\Hp Pavilion\Documents\MERNStack\third-party-repos\logseq-whisper-subtitles-server\logseq_whisper_subtitles_server\services.py", line 147, in <module>
> 
>     res_en = transcribe_audio("audio_english.mp3")
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Hp Pavilion\Documents\MERNStack\third-party-repos\logseq-whisper-subtitles-server\logseq_whisper_subtitles_server\services.py", line 84, in transcribe_audio
> 
>     transcribe = model.transcribe(audio=audio_path, verbose=True, initial_prompt="对于普通话句子，以中文简体输出")  # 避免繁体输出
> 
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Hp Pavilion\.conda\envs\logseq-transcription\Lib\site-packages\whisper\transcribe.py", line 121, in transcribe
> 
>     mel = log_mel_spectrogram(audio, padding=N_SAMPLES)
> 
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Hp Pavilion\.conda\envs\logseq-transcription\Lib\site-packages\whisper\audio.py", line 140, in log_mel_spectrogram
> 
>     audio = load_audio(audio)
> 
>             ^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Hp Pavilion\.conda\envs\logseq-transcription\Lib\site-packages\whisper\audio.py", line 59, in load_audio
> 
>     out = run(cmd, capture_output=True, check=True).stdout
> 
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Hp Pavilion\.conda\envs\logseq-transcription\Lib\subprocess.py", line 548, in run
> 
>     with Popen(*popenargs, **kwargs) as process:
> 
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "C:\Users\Hp Pavilion\.conda\envs\logseq-transcription\Lib\subprocess.py", line 1026, in __init__
> 
>     self._execute_child(args, executable, preexec_fn, close_fds,
> 
>   File "C:\Users\Hp Pavilion\.conda\envs\logseq-transcription\Lib\subprocess.py", line 1538, in _execute_child
> 
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> 
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
> ```

Is there a file called audio_english.mp3 in same directory? It's a english audio file for test.

**Comment by usoonees** [comment]
![image](https://github.com/usoonees/logseq-whisper-subtitles-server/assets/56818734/8c8b98ff-21ca-46c3-bb59-3f25be0c6f49)

@DocSJ1980 Could you verify if the `audio_english.mp3` file is located in the current directory?

**Comment by DocSJ1980** [comment]
Yes both of these files are there but same error. I tried changing the path but same result. Then I tried running the server anyway and calling from logseq to give whisper-subtitles but same result in the server.

![image](https://github.com/usoonees/logseq-whisper-subtitles-server/assets/106554079/d862c199-a13a-46d5-86c6-81000bfc0190)

**Comment by usoonees** [comment]
@DocSJ1980 Has `ffmpeg` been installed and is it accessible from the command line? You can test this by running the command `ffmpeg -version`.

**Comment by DocSJ1980** [comment]
![image](https://github.com/usoonees/logseq-whisper-subtitles-server/assets/106554079/e3419d35-ed35-4845-9fc6-788cce50b485)

**Comment by usoonees** [comment]
Try to reinstall ffmpeg  by `pip install ffmpeg-python`?

**Comment by DocSJ1980** [comment]
Wow. Issue resolved. Working perfectly on checking with services.py. Also working flawlessly in logseq.
