### ISSUE TITLE
Not supported source yet for local video files

### ISSUE THREAD

**Issue by mainrs** [usoonees/logseq-whisper-subtitles-server#4]
I got an error when trying to use the extension together with a local `.mp4` file.

![image](https://github.com/usoonees/logseq-whisper-subtitles-server/assets/5113257/b417c02b-5daa-4420-89e1-72a1ddd8c8ce)

**Comment by usoonees** [comment]
Could you share the local file path? Does it look like `![output.mp4](path)`?

**Comment by mainrs** [comment]
No, I used the embeded media package for it. It has this template format:

`{{renderer :media, /home/<more stuff>/video.mp4}}`

This is the package: https://github.com/sethyuan/logseq-plugin-media-ts

**Comment by usoonees** [comment]
Thanks for reporting, please try to pull the latest code.

**Comment by mainrs** [comment]
> Thanks for reporting, please try to pull the latest code.

Pulled the latest code, and it works! Thank you!
